services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pronoms-frontend
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - pronoms

networks:
  pronoms:
    external: true
